import type {
  BusinessImpact,
  DashboardKpis,
  DashboardYearMetrics,
  SessionState,
  SimulationResponse,
  YearlyResult,
} from "./types";
import type { AdversarialPersona } from "./types";
import type { Persona } from "../types";

const PLACEHOLDER_AVATARS = [
  "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?q=80&w=200&auto=format&fit=crop",
  "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=200&auto=format&fit=crop",
  "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?q=80&w=200&auto=format&fit=crop",
  "https://images.unsplash.com/photo-1544005313-94ddf0286df2?q=80&w=200&auto=format&fit=crop",
];

function vulnerabilityFromApproval(approval: number): string {
  if (approval < 30) return "Critical";
  if (approval < 45) return "High";
  if (approval < 60) return "Medium";
  return "Low";
}

function buildHeatmap(approval: number): number[] {
  return Array.from({ length: 10 }, (_, i) =>
    Math.max(5, Math.round(approval - i * (approval * 0.04)))
  );
}

function traitString(traits: Record<string, unknown>, keys: string[]): string {
  for (const key of keys) {
    const val = traits[key];
    if (val !== undefined && val !== null && val !== "") return String(val);
  }
  return "N/A";
}

function traitNumber(traits: Record<string, unknown>, keys: string[]): number {
  for (const key of keys) {
    const val = traits[key];
    if (typeof val === "number") return val;
    if (typeof val === "string") {
      const parsed = parseInt(val.replace(/[^0-9]/g, ""), 10);
      if (!Number.isNaN(parsed)) return parsed;
    }
  }
  return 650;
}

export function mapAdversarialPersonaToUI(
  persona: AdversarialPersona,
  index: number
): Persona {
  const traits = persona.traits ?? {};
  const creditScore = traitNumber(traits, [
    "credit_score",
    "creditScore",
    "academic_score",
    "technical_score",
  ]);
  const approvalProbability = Math.max(
    5,
    Math.min(95, Math.round((creditScore / 850) * 100))
  );
  const riskScore = Math.max(5, Math.min(95, 100 - approvalProbability));
  const gender = traitString(traits, ["gender"]);
  const incomeVal = traitNumber(traits, ["income", "family_income"]);
  const metadata =
    typeof persona.metadata === "object" && persona.metadata !== null
      ? (persona.metadata as Record<string, unknown>)
      : {};
  const reason =
    typeof persona.metadata === "string"
      ? persona.metadata
      : String(metadata.reason ?? "Adversarial edge-case generated by PersonaGenerator.");

  return {
    id: persona.persona_id || `adversarial-${index}`,
    name: traitString(traits, ["name"]) !== "N/A"
      ? traitString(traits, ["name"])
      : `Synthetic Candidate ${index + 1}`,
    role: "Adversarial Crash-Test Dummy",
    category: "credit",
    avatar: PLACEHOLDER_AVATARS[index % PLACEHOLDER_AVATARS.length],
    gender: gender !== "N/A" ? gender : "Unknown",
    income: `₹${incomeVal.toLocaleString("en-IN")} / month`,
    education: traitString(traits, ["education_level", "education"]),
    disability: traitString(traits, ["disability"]) !== "N/A"
      ? traitString(traits, ["disability"])
      : "None",
    location: traitString(traits, ["zip_code", "rural_urban", "location"]),
    approvalProbability,
    riskScore,
    creditScore,
    vulnerability: vulnerabilityFromApproval(approvalProbability),
    vulnerabilityDetail: reason,
    outcome:
      approvalProbability < 50
        ? "Rejected by automated scoring model — adversarial demographic cluster flagged."
        : "Approved with elevated manual review risk under current policy weights.",
    heatmap: buildHeatmap(approvalProbability),
    traits,
  };
}

export function mapAdversarialPersonasToUI(
  personas: AdversarialPersona[]
): Persona[] {
  return personas.map(mapAdversarialPersonaToUI);
}

const TIMELINE_BASE_YEAR = 2025;

export function simulationYearToCalendarYear(simYear: number): number {
  return TIMELINE_BASE_YEAR + simYear - 1;
}

export function calendarYearToSimulationYear(calendarYear: number): number {
  return calendarYear - TIMELINE_BASE_YEAR + 1;
}

export function mapYearlyResultToMetrics(
  result: YearlyResult
): DashboardYearMetrics {
  const { metrics, average_target_rate } = result;
  const fairness = Math.round(
    Math.max(0, Math.min(100, metrics.demographic_parity_ratio * 100))
  );
  const disparityEvolution = Math.round(
    Math.max(0, Math.min(100, Math.abs(metrics.demographic_parity_diff) * 100))
  );
  const approvalRate = Math.round(
    Math.max(0, Math.min(100, average_target_rate * 100))
  );
  const riskAccumulation = Math.round(
    Math.max(
      10,
      Math.min(100, (1 - metrics.disparate_impact) * 100 + disparityEvolution * 0.3)
    )
  );
  const feedbackScore = Math.round(
    Math.max(40, Math.min(100, metrics.demographic_parity_ratio * 95))
  );

  return {
    fairness,
    riskAccumulation,
    approvalRate,
    disparityEvolution,
    feedbackScore,
  };
}

export function mapYearlyResultsToTimeline(
  yearlyResults: YearlyResult[]
): Map<number, DashboardYearMetrics> {
  const timeline = new Map<number, DashboardYearMetrics>();
  for (const result of yearlyResults) {
    timeline.set(
      simulationYearToCalendarYear(result.year),
      mapYearlyResultToMetrics(result)
    );
  }
  return timeline;
}

function formatCohortSize(rowCount: number): string {
  if (rowCount >= 1_000_000) {
    return `${(rowCount / 1_000_000).toFixed(1)}M`;
  }
  if (rowCount >= 1_000) {
    return `${(rowCount / 1_000).toFixed(1)}K`;
  }
  return String(rowCount);
}

export function mapBusinessImpactToKpis(
  businessImpact: BusinessImpact | undefined
): Pick<
  DashboardKpis,
  "revenueDisplay" | "projectedFineDisplay" | "fineSubtitle" | "revenueSubtitle"
> {
  if (!businessImpact) {
    return {
      revenueDisplay: "—",
      projectedFineDisplay: "—",
      fineSubtitle: "Awaiting simulation",
      revenueSubtitle: "Awaiting simulation",
    };
  }

  const projectedFine =
    businessImpact.financial_loss_amount > 0
      ? businessImpact.currency_formatted
      : "₹0";

  return {
    revenueDisplay: businessImpact.currency_formatted,
    projectedFineDisplay: projectedFine,
    fineSubtitle: businessImpact.impact_statement,
    revenueSubtitle: "From API",
  };
}

export function mapSimulationToDashboardKpis(
  simulation: SimulationResponse | null,
  session: SessionState | null
): DashboardKpis {
  const latestYear =
    simulation?.yearly_results?.[simulation.yearly_results.length - 1];
  const latestMetrics = latestYear
    ? mapYearlyResultToMetrics(latestYear)
    : null;

  const businessKpis = mapBusinessImpactToKpis(simulation?.business_impact);

  const govScore = latestMetrics?.feedbackScore ?? 0;
  const compliancePct = latestYear
    ? Math.round(
        Math.max(0, Math.min(100, latestYear.metrics.disparate_impact * 100))
      )
    : 0;
  const fairnessPct = latestMetrics?.fairness ?? 0;

  const fairnessTrend =
    simulation && simulation.yearly_results.length >= 2
      ? simulation.yearly_results[simulation.yearly_results.length - 1].metrics
          .demographic_parity_ratio -
        simulation.yearly_results[0].metrics.demographic_parity_ratio
      : 0;

  return {
    govScore,
    compliancePct,
    fairnessPct,
    ...businessKpis,
    cohortDisplay: session ? formatCohortSize(session.row_count) : "—",
    govSubtitle: govScore >= 80 ? "▲ Stable governance" : "● Review required",
    complianceSubtitle:
      compliancePct >= 80 ? "▲ RBI Sandbox Pass" : "● Compliance gap",
    fairnessSubtitle:
      fairnessTrend < 0 ? "● Declining trend" : "▲ Improving trend",
  };
}

export function getMetricsForCalendarYear(
  simulation: SimulationResponse | null,
  calendarYear: number
): DashboardYearMetrics | null {
  if (!simulation?.yearly_results?.length) return null;

  const timeline = mapYearlyResultsToTimeline(simulation.yearly_results);
  const metrics = timeline.get(calendarYear);
  if (metrics) return metrics;

  const simYear = calendarYearToSimulationYear(calendarYear);
  const result = simulation.yearly_results.find((r) => r.year === simYear);
  return result ? mapYearlyResultToMetrics(result) : null;
}

export function getAvailableTimelineYears(
  simulation: SimulationResponse | null
): number[] {
  if (!simulation?.yearly_results?.length) {
    return Array.from({ length: 11 }, (_, i) => TIMELINE_BASE_YEAR + i);
  }
  return simulation.yearly_results.map((r) =>
    simulationYearToCalendarYear(r.year)
  );
}
